from pathlib import Path
from models.generate import StackSelection, GenerationOptions

SNIPPETS_DIR = Path(__file__).parent.parent / "snippets"


def _collect_env_vars(stack: StackSelection) -> str:
    """Reads env_vars.txt from each selected technology and combines them."""
    sections: list[str] = []

    candidates = [
        f"auth/{_auth_dir(stack.auth)}/env_vars.txt",
        f"database/{_db_dir(stack.database)}/env_vars.txt",
    ]

    for rel in candidates:
        path = SNIPPETS_DIR / rel
        if path.exists():
            sections.append(path.read_text(encoding="utf-8").strip())

    # Always add server URL var
    sections.append("# Server\nPORT=3000\nCLIENT_URL=http://localhost:5173")

    return "\n\n".join(sections)


def _auth_dir(auth: str) -> str:
    a = auth.lower()
    if "supabase" in a:
        return "supabase-auth"
    if "nextauth" in a:
        return "nextauth"
    if "firebase" in a:
        return "firebase-auth"
    return "auth0"


def _db_dir(db: str) -> str:
    d = db.lower()
    if "mongo" in d:
        return "mongodb"
    if "mysql" in d:
        return "mysql"
    if "supabase" in d:
        return "supabase"
    return "postgresql"


def _readme(stack: StackSelection, project_name: str) -> str:
    return f"""# {project_name}

Generated by [Skapta](https://skapta.dev).

## Stack

| Layer | Choice |
|---|---|
| Frontend | {stack.frontend} |
| Backend | {stack.backend} |
| Database | {stack.database} |
| Auth | {stack.auth} |
| Deployment | {stack.deployment} |

## Setup

1. **Fill in your environment variables**

   ```bash
   cp .env.example .env
   # Edit .env — fill in all required values
   ```

2. **Install dependencies**

   ```bash
   # Frontend
   cd client && npm install

   # Backend
   cd server && npm install
   ```

3. **Set up the database**

   ```bash
   cd server
   npx prisma generate
   npx prisma migrate dev --name init
   ```

4. **Start the dev servers**

   ```bash
   # In one terminal
   cd server && npm run dev

   # In another terminal
   cd client && npm run dev
   ```

   - Frontend: http://localhost:5173
   - Backend: http://localhost:3000

## Auth0 Setup

1. Create an application at https://manage.auth0.com
2. Set **Allowed Callback URLs**: `http://localhost:5173`
3. Set **Allowed Logout URLs**: `http://localhost:5173`
4. Set **Allowed Web Origins**: `http://localhost:5173`
5. Create an **API** and copy the identifier as `AUTH0_AUDIENCE` / `VITE_AUTH0_AUDIENCE`

## Deployment

See the included `docker-compose.yml` for local containerised setup, or deploy to {stack.deployment} using the included config.
"""


def _setup_sh(stack: StackSelection) -> str:
    return """#!/usr/bin/env bash
set -e

echo "Setting up project..."

if [ ! -f .env ]; then
  cp .env.example .env
  echo "Created .env from .env.example — fill in your credentials before starting."
fi

echo "Installing client dependencies..."
cd client && npm install && cd ..

echo "Installing server dependencies..."
cd server && npm install && cd ..

echo "Generating Prisma client..."
cd server && npx prisma generate && cd ..

echo ""
echo "Setup complete."
echo "Fill in .env, then run:"
echo "  cd server && npm run dev"
echo "  cd client && npm run dev"
"""


def _setup_bat(stack: StackSelection) -> str:
    return """@echo off
echo Setting up project...

if not exist .env (
  copy .env.example .env
  echo Created .env from .env.example -- fill in your credentials before starting.
)

echo Installing client dependencies...
cd client && npm install && cd ..

echo Installing server dependencies...
cd server && npm install && cd ..

echo Generating Prisma client...
cd server && npx prisma generate && cd ..

echo.
echo Setup complete.
echo Fill in .env, then run:
echo   cd server ^&^& npm run dev
echo   cd client ^&^& npm run dev
"""


def generate_shared_files(
    stack: StackSelection,
    options: GenerationOptions,
    project_name: str,
) -> dict[str, str]:
    env_content = _collect_env_vars(stack)
    return {
        ".env.example": env_content,
        "README.md": _readme(stack, project_name),
        "setup.sh": _setup_sh(stack),
        "setup.bat": _setup_bat(stack),
    }
