import re
from pathlib import Path
from models.generate import StackSelection, GenerationOptions

SNIPPETS_DIR = Path(__file__).parent.parent / "snippets"

_VAR_LINE = re.compile(r"^[A-Z][A-Z0-9_]*=")


def _auth_dir(auth: str) -> str:
    a = auth.lower()
    if "supabase" in a:
        return "supabase-auth"
    if "nextauth" in a:
        return "nextauth"
    if "firebase" in a:
        return "firebase-auth"
    return "auth0"


def _db_dir(db: str) -> str:
    d = db.lower()
    if "mongo" in d:
        return "mongodb"
    if "mysql" in d:
        return "mysql"
    if "supabase" in d:
        return "supabase"
    return "postgresql"


def _read_env_vars(stack: StackSelection) -> list[str]:
    """Collect var-assignment lines from each technology's env_vars.txt, deduplicated."""
    frontend = stack.frontend.lower()
    backend = stack.backend.lower()

    rels = [
        f"auth/{_auth_dir(stack.auth)}/env_vars.txt",
        f"database/{_db_dir(stack.database)}/env_vars.txt",
    ]

    seen: set[str] = set()
    lines: list[str] = []
    for rel in rels:
        path = SNIPPETS_DIR / rel
        if path.exists():
            for line in path.read_text(encoding="utf-8").splitlines():
                if _VAR_LINE.match(line):
                    var_name = line.split("=")[0]
                    if var_name not in seen:
                        seen.add(var_name)
                        lines.append(line.strip())

    # Server-only runtime vars -- not applicable to Next.js-only stacks.
    if "next" not in frontend or (backend and backend != "none"):
        lines.append("PORT=3000")
        lines.append("CLIENT_URL=http://localhost:5173")

    # Django needs a secret key (settings.py falls back to a dev value if unset).
    if "django" in backend:
        lines.append("DJANGO_SECRET_KEY=change-me-to-a-long-random-string")

    return lines


def _split_env(stack: StackSelection) -> tuple[str, str]:
    """Returns (client_env, server_env).

    VITE_* and NEXT_PUBLIC_* go to the client; everything else goes to the server.
    """
    client_lines: list[str] = []
    server_lines: list[str] = []

    for line in _read_env_vars(stack):
        if line.startswith("VITE_") or line.startswith("NEXT_PUBLIC_"):
            client_lines.append(line)
        else:
            server_lines.append(line)

    client = "# Frontend environment variables\n" + "\n".join(client_lines) + "\n"
    server = "# Backend environment variables\n" + "\n".join(server_lines) + "\n"
    return client, server


def _combined_env(stack: StackSelection) -> str:
    """All env vars in one file. For Next.js-only apps there is no client/server
    split -- the app reads its own `.env`, which must hold both NEXT_PUBLIC_* values
    and server-side secrets (e.g. NextAuth's AUTH_SECRET)."""
    return "# Environment variables\n" + "\n".join(_read_env_vars(stack)) + "\n"


# ---------------------------------------------------------------------------
# README
# ---------------------------------------------------------------------------

def _readme(stack: StackSelection, project_name: str) -> str:
    frontend = stack.frontend.lower()
    backend = stack.backend.lower()
    db = stack.database.lower()

    is_nextjs_only = "next" in frontend and (not backend or backend == "none")
    is_django = "django" in backend
    is_python = "fastapi" in backend or is_django
    has_docker = any("docker" in s.lower() for s in [stack.deployment] + stack.additional)

    stack_table = f"""| Layer | Choice |
|---|---|
| Frontend | {stack.frontend} |
| Backend | {stack.backend if backend and backend != "none" else "Next.js API routes"} |
| Database | {stack.database} |
| Auth | {stack.auth} |
| Deployment | {stack.deployment} |"""

    if is_nextjs_only:
        if "nextauth" in stack.auth.lower():
            return _readme_nextjs_nextauth(project_name, stack, stack_table)
        return _readme_nextjs(project_name, stack, stack_table)
    if is_django:
        return _readme_django(project_name, stack, stack_table, has_docker)
    if is_python:
        return _readme_python(project_name, stack, stack_table, has_docker)
    if "mongo" in db:
        return _readme_mern(project_name, stack, stack_table, has_docker)
    return _readme_pern(project_name, stack, stack_table, has_docker)


def _readme_nextjs(project_name: str, stack: StackSelection, stack_table: str) -> str:
    return f"""# {project_name}

Generated by [Skapta](https://skapta.dev).

## Stack

{stack_table}

## Setup

1. **Configure environment variables**

   ```bash
   cp client/.env.example client/.env.local
   # Edit client/.env.local with your Supabase credentials
   ```

2. **Install dependencies**

   ```bash
   cd client && npm install
   ```

3. **Start the dev server**

   ```bash
   cd client && npm run dev
   ```

   App runs at http://localhost:3000

`./setup.sh` (Mac/Linux) or `setup.bat` (Windows) handles steps 1 and 2.

## Supabase Setup

1. Create a project at https://supabase.com
2. Go to **Project Settings -> API** and copy:
   - **Project URL** -> `NEXT_PUBLIC_SUPABASE_URL`
   - **anon public key** -> `NEXT_PUBLIC_SUPABASE_ANON_KEY`
3. Enable an auth provider under **Authentication -> Providers** (GitHub, Google, etc.)
4. Set the **Site URL** to `http://localhost:3000`
5. Add `http://localhost:3000/auth/callback` to **Redirect URLs**

## Deployment

Push to GitHub and import the repo into **{stack.deployment}**.
Add `NEXT_PUBLIC_SUPABASE_URL` and `NEXT_PUBLIC_SUPABASE_ANON_KEY` in your project's environment settings.
"""


def _readme_nextjs_nextauth(project_name: str, stack: StackSelection, stack_table: str) -> str:
    return f"""# {project_name}

Generated by [Skapta](https://skapta.dev).

## Stack

{stack_table}

## Setup

1. **Configure environment variables**

   ```bash
   cp client/.env.example client/.env.local
   # Edit client/.env.local with your AUTH_SECRET and GitHub OAuth credentials
   ```

2. **Install dependencies**

   ```bash
   cd client && npm install
   ```

3. **Start the dev server**

   ```bash
   cd client && npm run dev
   ```

   App runs at http://localhost:3000

`./setup.sh` (Mac/Linux) or `setup.bat` (Windows) handles steps 1 and 2.

## NextAuth (Auth.js) Setup

1. Generate a session secret:

   ```bash
   openssl rand -base64 32
   ```

   Set the output as `AUTH_SECRET` in `.env.local`.

2. Create a **GitHub OAuth App** (GitHub -> Settings -> Developer settings -> OAuth Apps):
   - **Homepage URL**: `http://localhost:3000`
   - **Authorization callback URL**: `http://localhost:3000/api/auth/callback/github`
   - Set the Client ID as `AUTH_GITHUB_ID` and the Client Secret as `AUTH_GITHUB_SECRET`

3. Auth uses the JWT strategy, so no database is needed. To add more providers, edit `auth.ts`.

## Deployment

Push to GitHub and import the repo into **{stack.deployment}**.
Set `AUTH_SECRET`, `AUTH_GITHUB_ID`, and `AUTH_GITHUB_SECRET` in your project's environment settings.
Update the GitHub OAuth callback URL to your production domain before going live.
"""


def _readme_pern(project_name: str, stack: StackSelection, stack_table: str, has_docker: bool) -> str:
    docker_note = "\nSee `docker-compose.yml` for a local setup with Docker." if has_docker else ""
    return f"""# {project_name}

Generated by [Skapta](https://skapta.dev).

## Stack

{stack_table}

## Setup

1. **Configure environment variables**

   ```bash
   cp client/.env.example client/.env
   cp server/.env.example server/.env
   # Edit both files with your credentials
   ```

2. **Install dependencies**

   ```bash
   cd client && npm install && cd ..
   cd server && npm install && cd ..
   ```

3. **Set up the database**

   ```bash
   cd server
   npx prisma generate
   npx prisma db push
   cd ..
   ```

4. **Start the dev servers**

   ```bash
   # terminal 1
   cd server && npm run dev

   # terminal 2
   cd client && npm run dev
   ```

   - Frontend: http://localhost:5173
   - Backend: http://localhost:3000

`./setup.sh` (Mac/Linux) or `setup.bat` (Windows) handles steps 1 through 3.

## Auth0 Setup

1. Create a Single Page Application at https://manage.auth0.com
2. Set **Allowed Callback URLs** to `http://localhost:5173/dashboard`
3. Set **Allowed Logout URLs** to `http://localhost:5173`
4. Set **Allowed Web Origins** to `http://localhost:5173`
5. Create an API and copy its identifier into `AUTH0_AUDIENCE` and `VITE_AUTH0_AUDIENCE`

## Deployment

Deploy to **{stack.deployment}** using the `railway.toml` in the project root.{docker_note}
"""


def _readme_mern(project_name: str, stack: StackSelection, stack_table: str, has_docker: bool) -> str:
    docker_note = "\nSee `docker-compose.yml` for a local setup with Docker." if has_docker else ""
    return f"""# {project_name}

Generated by [Skapta](https://skapta.dev).

## Stack

{stack_table}

## Setup

1. **Configure environment variables**

   ```bash
   cp client/.env.example client/.env
   cp server/.env.example server/.env
   # Edit both files with your credentials
   ```

2. **Install dependencies**

   ```bash
   cd client && npm install && cd ..
   cd server && npm install && cd ..
   ```

3. **Start the dev servers**

   ```bash
   # terminal 1
   cd server && npm run dev

   # terminal 2
   cd client && npm run dev
   ```

   - Frontend: http://localhost:5173
   - Backend: http://localhost:3000

`./setup.sh` (Mac/Linux) or `setup.bat` (Windows) handles steps 1 and 2.

## MongoDB Setup

**Local:** Install MongoDB Community Edition and start `mongod`. The default URI `mongodb://localhost:27017/myapp` works without any changes.

**Atlas:** Create a free cluster at https://cloud.mongodb.com, copy the connection string, and set `MONGODB_URI` in `server/.env`.

## Auth0 Setup

1. Create a Single Page Application at https://manage.auth0.com
2. Set **Allowed Callback URLs** to `http://localhost:5173/dashboard`
3. Set **Allowed Logout URLs** to `http://localhost:5173`
4. Set **Allowed Web Origins** to `http://localhost:5173`
5. Create an API and copy its identifier into `AUTH0_AUDIENCE` and `VITE_AUTH0_AUDIENCE`

## Deployment

Deploy to **{stack.deployment}** using the `railway.toml` in the project root.{docker_note}
"""


def _readme_python(project_name: str, stack: StackSelection, stack_table: str, has_docker: bool) -> str:
    docker_note = "\nSee `docker-compose.yml` for a local setup with Docker." if has_docker else ""
    return f"""# {project_name}

Generated by [Skapta](https://skapta.dev).

## Stack

{stack_table}

## Setup

1. **Configure environment variables**

   ```bash
   cp client/.env.example client/.env
   cp server/.env.example server/.env
   # Edit both files with your credentials
   ```

2. **Install dependencies**

   ```bash
   cd client && npm install && cd ..
   cd server && pip install -r requirements.txt && cd ..
   ```

3. **Start the dev servers**

   ```bash
   # terminal 1
   cd server && uvicorn main:app --reload

   # terminal 2
   cd client && npm run dev
   ```

   - Frontend: http://localhost:5173
   - Backend: http://localhost:3000
   - API docs: http://localhost:3000/docs

`./setup.sh` (Mac/Linux) or `setup.bat` (Windows) handles steps 1 and 2.

## Auth0 Setup

1. Create a Single Page Application at https://manage.auth0.com
2. Set **Allowed Callback URLs** to `http://localhost:5173/dashboard`
3. Set **Allowed Logout URLs** to `http://localhost:5173`
4. Set **Allowed Web Origins** to `http://localhost:5173`
5. Create an API and copy its identifier into `AUTH0_AUDIENCE` and `VITE_AUTH0_AUDIENCE`

## Deployment

Deploy to **{stack.deployment}** using the `railway.toml` in the project root.{docker_note}
"""


def _readme_django(project_name: str, stack: StackSelection, stack_table: str, has_docker: bool) -> str:
    docker_note = "\nSee `docker-compose.yml` for a local setup with Docker." if has_docker else ""
    return f"""# {project_name}

Generated by [Skapta](https://skapta.dev).

## Stack

{stack_table}

## Setup

1. **Configure environment variables**

   ```bash
   cp client/.env.example client/.env
   cp server/.env.example server/.env
   # Edit both files -- make sure DJANGO_SECRET_KEY and DATABASE_URL are set
   ```

2. **Install dependencies**

   ```bash
   cd client && npm install && cd ..
   cd server && pip install -r requirements.txt && cd ..
   ```

3. **Run database migrations**

   ```bash
   cd server && python manage.py migrate && cd ..
   ```

4. **Start the dev servers**

   ```bash
   # terminal 1
   cd server && python manage.py runserver 0.0.0.0:3000

   # terminal 2
   cd client && npm run dev
   ```

   - Frontend: http://localhost:5173
   - Backend: http://localhost:3000

`./setup.sh` (Mac/Linux) or `setup.bat` (Windows) handles steps 1 through 3.

## Auth0 Setup

1. Create a Single Page Application at https://manage.auth0.com
2. Set **Allowed Callback URLs** to `http://localhost:5173/dashboard`
3. Set **Allowed Logout URLs** to `http://localhost:5173`
4. Set **Allowed Web Origins** to `http://localhost:5173`
5. Create an API and copy its identifier into `AUTH0_AUDIENCE` and `VITE_AUTH0_AUDIENCE`

## Deployment

Deploy to **{stack.deployment}** using the `railway.toml` or `render.yaml` in the project root.{docker_note}
"""


# ---------------------------------------------------------------------------
# Setup scripts
# ---------------------------------------------------------------------------

def _setup_sh_nextjs(creds: str = "Supabase credentials") -> str:
    return f"""#!/usr/bin/env bash
set -e

echo "Setting up project..."

if [ ! -f client/.env.local ]; then
  cp client/.env.example client/.env.local
  echo "Created client/.env.local -- fill in your {creds} before starting."
fi

echo "Installing dependencies..."
(cd client && npm install)

echo ""
echo "Setup complete."
echo "Fill in client/.env.local, then run:"
echo "  cd client && npm run dev"
"""


def _setup_bat_nextjs(creds: str = "Supabase credentials") -> str:
    return f"""@echo off
echo Setting up project...

if not exist client\\.env.local (
  copy client\\.env.example client\\.env.local
  echo Created client\\.env.local -- fill in your {creds} before starting.
)

echo Installing dependencies...
cd client && npm install && cd ..

echo.
echo Setup complete.
echo Fill in client\\.env.local, then run:
echo   cd client ^&^& npm run dev
"""


def _setup_sh_node(stack: StackSelection) -> str:
    db = stack.database.lower()
    use_prisma = "mongo" not in db and "supabase" not in db

    prisma_block = """
echo "Generating Prisma client and pushing schema..."
(cd server && npx prisma generate && npx prisma db push)
""" if use_prisma else ""

    return f"""#!/usr/bin/env bash
set -e

echo "Setting up project..."

if [ ! -f client/.env ]; then
  cp client/.env.example client/.env
  echo "Created client/.env -- fill in your credentials before starting."
fi

if [ ! -f server/.env ]; then
  cp server/.env.example server/.env
  echo "Created server/.env -- fill in your credentials before starting."
fi

echo "Installing client dependencies..."
(cd client && npm install)

echo "Installing server dependencies..."
(cd server && npm install)
{prisma_block}
echo ""
echo "Setup complete."
echo "Fill in client/.env and server/.env, then run:"
echo "  cd server && npm run dev"
echo "  cd client && npm run dev"
"""


def _setup_bat_node(stack: StackSelection) -> str:
    db = stack.database.lower()
    use_prisma = "mongo" not in db and "supabase" not in db

    prisma_block = """
echo Generating Prisma client and pushing schema...
cd server && npx prisma generate && npx prisma db push && cd ..
""" if use_prisma else ""

    return f"""@echo off
echo Setting up project...

if not exist client\\.env (
  copy client\\.env.example client\\.env
  echo Created client\\.env -- fill in your credentials before starting.
)

if not exist server\\.env (
  copy server\\.env.example server\\.env
  echo Created server\\.env -- fill in your credentials before starting.
)

echo Installing client dependencies...
cd client && npm install && cd ..

echo Installing server dependencies...
cd server && npm install && cd ..
{prisma_block}
echo.
echo Setup complete.
echo Fill in client\\.env and server\\.env, then run:
echo   cd server ^&^& npm run dev
echo   cd client ^&^& npm run dev
"""


def _setup_sh_python() -> str:
    return """#!/usr/bin/env bash
set -e

echo "Setting up project..."

if [ ! -f client/.env ]; then
  cp client/.env.example client/.env
  echo "Created client/.env -- fill in your credentials before starting."
fi

if [ ! -f server/.env ]; then
  cp server/.env.example server/.env
  echo "Created server/.env -- fill in your credentials before starting."
fi

echo "Installing client dependencies..."
(cd client && npm install)

echo "Installing server dependencies..."
(cd server && pip install -r requirements.txt)

echo ""
echo "Setup complete."
echo "Fill in client/.env and server/.env, then run:"
echo "  cd server && uvicorn main:app --reload"
echo "  cd client && npm run dev"
"""


def _setup_bat_python() -> str:
    return """@echo off
echo Setting up project...

if not exist client\\.env (
  copy client\\.env.example client\\.env
  echo Created client\\.env -- fill in your credentials before starting.
)

if not exist server\\.env (
  copy server\\.env.example server\\.env
  echo Created server\\.env -- fill in your credentials before starting.
)

echo Installing client dependencies...
cd client && npm install && cd ..

echo Installing server dependencies...
cd server && pip install -r requirements.txt && cd ..

echo.
echo Setup complete.
echo Fill in client\\.env and server\\.env, then run:
echo   cd server ^&^& uvicorn main:app --reload
echo   cd client ^&^& npm run dev
"""


def _setup_sh_django() -> str:
    return """#!/usr/bin/env bash
set -e

echo "Setting up project..."

if [ ! -f client/.env ]; then
  cp client/.env.example client/.env
  echo "Created client/.env -- fill in your credentials before starting."
fi

if [ ! -f server/.env ]; then
  cp server/.env.example server/.env
  echo "Created server/.env -- fill in your credentials before starting."
fi

echo "Installing client dependencies..."
(cd client && npm install)

echo "Installing server dependencies..."
(cd server && pip install -r requirements.txt)

echo "Creating database tables..."
(cd server && python manage.py migrate)

echo ""
echo "Setup complete."
echo "Fill in client/.env and server/.env, then run:"
echo "  cd server && python manage.py runserver 0.0.0.0:3000"
echo "  cd client && npm run dev"
"""


def _setup_bat_django() -> str:
    return """@echo off
echo Setting up project...

if not exist client\\.env (
  copy client\\.env.example client\\.env
  echo Created client\\.env -- fill in your credentials before starting.
)

if not exist server\\.env (
  copy server\\.env.example server\\.env
  echo Created server\\.env -- fill in your credentials before starting.
)

echo Installing client dependencies...
cd client && npm install && cd ..

echo Installing server dependencies...
cd server && pip install -r requirements.txt && cd ..

echo Creating database tables...
cd server && python manage.py migrate && cd ..

echo.
echo Setup complete.
echo Fill in client\\.env and server\\.env, then run:
echo   cd server ^&^& python manage.py runserver 0.0.0.0:3000
echo   cd client ^&^& npm run dev
"""


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def generate_shared_files(
    stack: StackSelection,
    options: GenerationOptions,
    project_name: str,
) -> dict[str, str]:
    frontend = stack.frontend.lower()
    backend = stack.backend.lower()
    is_django = "django" in backend
    is_python = "fastapi" in backend or is_django
    is_nextjs_only = "next" in frontend and (not backend or backend == "none")

    client_env, server_env = _split_env(stack)
    readme = _readme(stack, project_name)

    if is_nextjs_only:
        # Next.js reads a single .env (no client/server split) -- include all vars,
        # incl. server-side secrets like NextAuth's AUTH_SECRET.
        is_nextauth = "nextauth" in stack.auth.lower()
        creds = "NextAuth credentials (AUTH_SECRET + GitHub OAuth)" if is_nextauth else "Supabase credentials"
        return {
            "client/.env.example": _combined_env(stack),
            "README.md": readme,
            "setup.sh": _setup_sh_nextjs(creds),
            "setup.bat": _setup_bat_nextjs(creds),
        }

    if is_django:
        return {
            "client/.env.example": client_env,
            "server/.env.example": server_env,
            "README.md": readme,
            "setup.sh": _setup_sh_django(),
            "setup.bat": _setup_bat_django(),
        }

    if is_python:
        return {
            "client/.env.example": client_env,
            "server/.env.example": server_env,
            "README.md": readme,
            "setup.sh": _setup_sh_python(),
            "setup.bat": _setup_bat_python(),
        }

    # Node.js (PERN or MERN)
    return {
        "client/.env.example": client_env,
        "server/.env.example": server_env,
        "README.md": readme,
        "setup.sh": _setup_sh_node(stack),
        "setup.bat": _setup_bat_node(stack),
    }
