import re
from pathlib import Path
from models.generate import StackSelection, GenerationOptions

SNIPPETS_DIR = Path(__file__).parent.parent / "snippets"

_VAR_LINE = re.compile(r"^[A-Z][A-Z0-9_]*=")


def _read_env_vars(stack: StackSelection) -> list[str]:
    """Collects raw var-assignment lines from each selected technology's env_vars.txt."""
    rels = [
        f"auth/{_auth_dir(stack.auth)}/env_vars.txt",
        f"database/{_db_dir(stack.database)}/env_vars.txt",
    ]

    lines: list[str] = []
    for rel in rels:
        path = SNIPPETS_DIR / rel
        if path.exists():
            for line in path.read_text(encoding="utf-8").splitlines():
                if _VAR_LINE.match(line):
                    lines.append(line.strip())

    # Server-only runtime vars
    lines.append("PORT=3000")
    lines.append("CLIENT_URL=http://localhost:5173")
    return lines


def _split_env(stack: StackSelection) -> tuple[str, str]:
    """Returns (client_env, server_env). VITE_* vars go to the client, the rest to the server."""
    client_lines: list[str] = []
    server_lines: list[str] = []

    for line in _read_env_vars(stack):
        if line.startswith("VITE_"):
            client_lines.append(line)
        else:
            server_lines.append(line)

    client = "# Frontend environment variables\n" + "\n".join(client_lines) + "\n"
    server = "# Backend environment variables\n" + "\n".join(server_lines) + "\n"
    return client, server


def _auth_dir(auth: str) -> str:
    a = auth.lower()
    if "supabase" in a:
        return "supabase-auth"
    if "nextauth" in a:
        return "nextauth"
    if "firebase" in a:
        return "firebase-auth"
    return "auth0"


def _db_dir(db: str) -> str:
    d = db.lower()
    if "mongo" in d:
        return "mongodb"
    if "mysql" in d:
        return "mysql"
    if "supabase" in d:
        return "supabase"
    return "postgresql"


def _readme(stack: StackSelection, project_name: str) -> str:
    return f"""# {project_name}

Generated by [Skapta](https://skapta.dev).

## Stack

| Layer | Choice |
|---|---|
| Frontend | {stack.frontend} |
| Backend | {stack.backend} |
| Database | {stack.database} |
| Auth | {stack.auth} |
| Deployment | {stack.deployment} |

## Setup

1. **Fill in your environment variables**

   ```bash
   cp client/.env.example client/.env
   cp server/.env.example server/.env
   # Edit each .env — fill in all required values
   ```

2. **Install dependencies**

   ```bash
   cd client && npm install && cd ..
   cd server && npm install && cd ..
   ```

3. **Set up the database**

   ```bash
   cd server
   npx prisma generate
   npx prisma migrate dev --name init
   cd ..
   ```

4. **Start the dev servers**

   ```bash
   # In one terminal
   cd server && npm run dev

   # In another terminal
   cd client && npm run dev
   ```

   - Frontend: http://localhost:5173
   - Backend: http://localhost:3000

Or run `./setup.sh` (Mac/Linux) / `setup.bat` (Windows) to do steps 1–3 automatically.

## Auth0 Setup

1. Create an application at https://manage.auth0.com (Single Page Application)
2. Set **Allowed Callback URLs**: `http://localhost:5173`
3. Set **Allowed Logout URLs**: `http://localhost:5173`
4. Set **Allowed Web Origins**: `http://localhost:5173`
5. Create an **API** and copy the identifier as `AUTH0_AUDIENCE` / `VITE_AUTH0_AUDIENCE`

## Deployment

See the included `docker-compose.yml` for local containerised setup, or deploy to {stack.deployment} using the included config.
"""


def _setup_sh() -> str:
    return """#!/usr/bin/env bash
set -e

echo "Setting up project..."

if [ ! -f client/.env ]; then
  cp client/.env.example client/.env
  echo "Created client/.env — fill in your credentials before starting."
fi

if [ ! -f server/.env ]; then
  cp server/.env.example server/.env
  echo "Created server/.env — fill in your credentials before starting."
fi

echo "Installing client dependencies..."
(cd client && npm install)

echo "Installing server dependencies..."
(cd server && npm install)

echo "Generating Prisma client..."
(cd server && npx prisma generate)

echo ""
echo "Setup complete."
echo "Fill in client/.env and server/.env, then run:"
echo "  cd server && npm run dev"
echo "  cd client && npm run dev"
"""


def _setup_bat() -> str:
    return """@echo off
echo Setting up project...

if not exist client\\.env (
  copy client\\.env.example client\\.env
  echo Created client\\.env -- fill in your credentials before starting.
)

if not exist server\\.env (
  copy server\\.env.example server\\.env
  echo Created server\\.env -- fill in your credentials before starting.
)

echo Installing client dependencies...
cd client && npm install && cd ..

echo Installing server dependencies...
cd server && npm install && cd ..

echo Generating Prisma client...
cd server && npx prisma generate && cd ..

echo.
echo Setup complete.
echo Fill in client\\.env and server\\.env, then run:
echo   cd server ^&^& npm run dev
echo   cd client ^&^& npm run dev
"""


def generate_shared_files(
    stack: StackSelection,
    options: GenerationOptions,
    project_name: str,
) -> dict[str, str]:
    client_env, server_env = _split_env(stack)
    return {
        "client/.env.example": client_env,
        "server/.env.example": server_env,
        "README.md": _readme(stack, project_name),
        "setup.sh": _setup_sh(),
        "setup.bat": _setup_bat(),
    }
