import type { Metadata } from 'next'
import './globals.css'

// Auth0 / Firebase: uncomment the line below -- AuthProvider lives in
// src/providers/AuthProvider.tsx (generated from your auth provider snippet).
// Supabase: leave commented out -- session is cookie-based, no context needed.
// import { AuthProvider } from '@/src/providers/AuthProvider'

export const metadata: Metadata = {
  title: '{{PROJECT_NAME}}',
  description: 'Generated by Skapta',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Auth0 / Firebase: wrap children in <AuthProvider>{children}</AuthProvider>
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
