import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: '{{PROJECT_NAME}}',
  description: 'Generated by Skapta',
}

// Supabase Auth is cookie-based: the session lives in HTTP-only cookies that the
// middleware refreshes on every request, and server/browser clients read it
// directly. No React context provider is needed at the root.
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
